export const SET_PHOTO_FIELD = 'SET_PHOTO_FIELD';

export const ADD_PHOTO_REQUEST = 'ADD_PHOTO_REQUEST';
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS';
export const ADD_PHOTO_ERROR = 'ADD_PHOTO_ERROR';
