export const SET_LOCATION_FIELD = 'SET_LOCATION_FIELD';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const NEW_LOCATION_REQUEST = 'NEW_LOCATION_REQUEST';
export const NEW_LOCATION_SUCCESS = 'NEW_LOCATION_SUCCESS';
export const NEW_LOCATION_ERROR = 'NEW_LOCATION_ERROR';
