export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
